# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_person'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('published', models.DateTimeField(blank=True, default=None, null=True)),
                ('body', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('sequence', models.PositiveIntegerField()),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Person')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qas', to='content.Interview')),
            ],
        ),
    ]
